target := "target"
arch := "aarch64"

# Build the kernel.
[group('build')]
[doc('Build the kernel')]
build:
	mkdir -p {{target/arch}}
	zig build \
		-Doptimize=Debug \
		-p {{target/arch}} \
		--prefix-exe-dir .
	llvm-objcopy -O binary {{target/arch/"kernel.elf"}} {{target/arch/"kernel8.img"}}

# Build the boot filesystem image.
[group('build')]
[doc('Build the boot filesystem image')]
bootfs:
	mkdir -p {{target}}

# Clean up build artifacts.
[group('build')]
[doc('Clean up build artifacts')]
clean:
	rm -rf {{target}}
